### ISSUE TITLE
Make sure that 404 errors return a JSON error.

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#24]

**Comment by mostlygeek** [comment]
I think we should get rid of the [404 errors](https://github.com/mozilla/PollBot/blob/master/pollbot/api.yaml#L213-L216) in the API spec entirely: 

```
        "404":
          description: "Release notes not found on mozilla.org"
          schema:
$ref: "#/definitions/errorResponse"
```

Giving a 404 meaning like, "release notes doesn't exist", implies that we should also give 503's meaning too. For example, if our bedrock scraper fails due to the HTML changing. 

I suggest we do this: 

* Use 200's for successes and __expected/anticipated__ upstream failures. 
* Use 400 for understanding requests from clients. 
* Use 500 for unexpected errors in Pollbot.

**Comment by Natim** [comment]
The 404 is more for when the product doesn't exists, not when the version doesn't exists.

**Comment by mostlygeek** [comment]
When would you use a 404 vs `status:"missing"` (link in [api.yaml](https://github.com/mozilla/PollBot/blob/master/pollbot/api.yaml#L227))?

**Comment by Natim** [comment]
> When would you use a 404

For a product we don't support yet for instance, as if the resource doesn't exists.
However we could probably return a 400 in that case but it would mean that a parameter is wrong or missing while the resource name is not really a parameter in the scope of HTTP 400.

**Comment by Natim** [comment]
The difference being:
- missing: The resource exists and we now that the answer for the check is missing

404: The resource was not found and we don't know what you are trying to ask for.
