### ISSUE TITLE
Bot to check download links on Bedrock (mozilla.org) has been updated

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/PollBot#4]
The page https://www.mozilla.org/en-US/firefox/all/ contains the latest available releases. The bot to check this page to make sure a build exists and is available for download. 

The way mozilla.org (bedrock) is updated is from pmac's [comment](https://github.com/mozilla/PollBot/issues/4#issuecomment-319687274) below:

1. [A job in Jenkins](https://ci.us-west.moz.works/blue/organizations/jenkins/product-details-json-watch/activity/) checks product-details.mozilla.org for updates every 15 min.
2. If updates are detected and validated (it makes sure that build definitions exist for all versions since that is spread across multiple files) the changes are checked into a [repo on github](https://github.com/mozilla/product-details-json) by the Jenkins job.
3. Bedrock runs a task every 15 min to pull new p-d data from said github repo into its database.
4. Once bedrock is serving the updated p-d data it takes another 15 to 30 min for the CDN cache to expire and show the new page contents to end-users.

**Comment by mostlygeek** [comment]
@pmclanahan does Bedrock have an API for checking the download links it is publishing? Is scraping the HTML the best way?

**Comment by pmac** [comment]
It's probably best to look at the links and make sure they're what you expect. What bedrock thinks are the current versions are included in data attributes on the `html` tag on most pages. At the moment you can see `data-latest-firefox="54.0.1"` if you view source on the home page. It also lists the latest ESR release, but none of the pre-release channels.

**Comment by mostlygeek** [comment]
@pmac can you provide some info about how bedrock's download links are updated? 
I put my assumptions in the description but I'm not sure if they are accurate.

**Comment by Natim** [comment]
This only works for the last released version, is this what we want? Is it a dashboard to display information about the last released version?

**Comment by pmac** [comment]
@mostlygeek it's not 100% accurate, but it's mostly there. What happens is this:

1. [A job in Jenkins](https://ci.us-west.moz.works/blue/organizations/jenkins/product-details-json-watch/activity/) checks product-details.mozilla.org for updates every 15 min.
2. If updates are detected and validated (it makes sure that build definitions exist for all versions since that is spread across multiple files) the changes are checked into a [repo on github](https://github.com/mozilla/product-details-json) by the Jenkins job.
3. Bedrock runs a task every 15 min to pull new p-d data from said github repo into its database.
4. Once bedrock is serving the updated p-d data it takes another 15 to 30 min for the CDN cache to expire and show the new page contents to end-users.

**Comment by Natim** [comment]
I've seen that we have https://www.mozilla.org/en-US/firefox/all/ but is it possible to have this page with a specific release of Firefox? https://www.mozilla.org/en-US/firefox/all/52.0/ for instance?

How can we check that a previous version was in Bedrock if it is not the last one?

**Comment by pmac** [comment]
We never offer old downloads on the site. You can see all previous releases and get to their release notes via this page however:

https://www.mozilla.org/en-US/firefox/releases/

The data there is also just a representation of the data in product-details.

**Comment by pmac** [comment]
Another FYI in case this wasn't clear, there are /all pages for the other channels as well:

* https://www.mozilla.org/en-US/firefox/beta/all/
* https://www.mozilla.org/en-US/firefox/developer/all/
* https://www.mozilla.org/en-US/firefox/nightly/all/

**Comment by Natim** [comment]
This helps thanks :)
