### ISSUE TITLE
How do we talk to ShipIt v1? 

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/PollBot#69]
PollBot will run inside the cloudops AWS network. However, shipit runs inside WebOps' network. What is the easiest way for PollBot to talk to ShipIt endpoints? 

The original use case #37

**Comment by Natim** [comment]
@bqbn any idea about that one?

**Comment by mostlygeek** [comment]
talked to @amyrrich and she suggested that the best route would be to use the VPN.

**Comment by mostlygeek** [comment]
Another option would be to have a proxy server. Pollbot talks to the proxy, which maintains and routes requests to ShipIt. The way traffic is routed to ShipIt should be determined by cloudops. Our code should just worry about sending appropriate HTTP requests.

**Comment by bqbn** [comment]
Who are allowed to access pollbot? Is it anyone on the Internet, or just Mozilla employees? 

I'm asking because Mozilla employees can log onto the VPN, others cannot.

**Comment by Natim** [comment]
We don't want people to have to log into the VPN to access PollBot.

**Comment by mostlygeek** [comment]
> We don't want people to have to log into the VPN to access PollBot.

The server pollbot runs on should use OpenVPN to make connect to the VPN. Then pollbot's request to shipit would just route appropriately.  This sucks since we run multiple servers for redundancy so it means one VPN connection/server.

**Comment by jvehent** [comment]
You cannot use the corp openvpn for this. It isn't suitable for long lived connections.

**Comment by amyrrich** [comment]
My suggestion was an ipsec tunnel between the AWS VPC and the scl3 (hardware) firewall.

**Comment by bqbn** [comment]
Well, I guess the degree of suckness depends on how many pollbot instances we need?

To that end, can you lmk

1. what/who is going to use pollbot?
2. estimated amount of traffic for pollbot?
3. also is pollbot going to be only on -stage, or -stage and -prod? there is a bugzilla ticket that's to set it up on -stage, it didn't mention -prod, so I want to ask.

**Comment by jvehent** [comment]
Can shipit publish the data over to pollbot instead?

**Comment by mostlygeek** [comment]
> Can shipit publish the data over to pollbot instead?

It's not called SubmitBot. ;)

**Comment by Natim** [comment]
> @bqbn :
> 1. what/who is going to use pollbot?

Mainly Release engineenering teams. 

> 2. estimated amount of traffic for pollbot?

About 20-50 connections per hour at release time.

> 3. is pollbot going to be only on -stage there is a bugzilla ticket that's to set it up on -stage, it didn't mention -prod, so I want to ask.

Pollbot can probably be deployed only in prod actually because there is not database or state of any kinds. (appart from the VPN access matter)

> @jvehent : Can shipit publish the data over to pollbot instead?

ShipIt already does that with Product-Details, we can probably stick to product-details for now but the plan was to also check ShipIt to see if the problem in the check was due to ShipIt not publishing or ProductDetails not replicating.

If we plan on publishing data from shipit to PollBot we add yet another place for the thing to fail.

> @amyrrich : My suggestion was an ipsec tunnel between the AWS VPC and the scl3 (hardware) firewall.

Would it be possible to have a VLAN between ShipIt and Pollbot with both of them sharing an IP network? Is it the same thing that you are suggesting?

**Comment by amyrrich** [comment]
Yes, the ipsec tunnel allows your instance to have an interface on the 10 network in your VPC. Here's how we set them up:

You receive an subnet allocation from netops in the 10 address space.
You create a VLAN in your AWS account with that address space.
You request netops to set up their end of the ipsec tunnel and give you a BGP ASN and IP.
You use the ASN and IP to set up a ipsec tunnel "VPN" in your VPC: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpn-connections.html

You could alternatively run an ec2 instance and connect your end of the tunnel there, but it's more of a pain to do so.

If you intend to make pollbot publicly accessible, you'll definitely want some sort of sec review since there would now be a public interface with access to our internal network.

**Comment by bqbn** [comment]
@jasonthomas informed me that shipit has a public API here: https://wiki.mozilla.org/Release_Management/Product_details

Can we use the endpoint in that document so we don't have to deal with VPN and the overhead that comes with it?

**Comment by Natim** [comment]
Product details is something we already use.

> >    @jvehent : Can shipit publish the data over to pollbot instead?
>
> ShipIt already does that with Product-Details, we can probably stick to product-details for now but the plan was to also check ShipIt to see if the problem in the check was due to ShipIt not publishing or ProductDetails not replicating.

**Comment by jvehent** [comment]
If ShipIt already has a public API and we already talk to it, wouldn't be a whole lot easier to add the data PollBot wants to access to that public API?

**Comment by Natim** [comment]
The goal of PollBot is to help Releng to investigate what is failing during the release.
We already have a check for Product-Details we just want to see if when ProductDetails fails it is because ShipIt didn't publish the data or if Product-Details didn't replicate it yet.

**Comment by Natim** [comment]
After discussions with @sylvestre and @jvehent it seems that we can avoid using a VPN for now.
We will reconsider if we need other checks to VPN API's later.
