### ISSUE TITLE
Push or pull?

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/PollBot#9]
In our meeting today we discovered that it's not clear what part of PollBot actually gathers data from bedrock, et. al. I heard two possibilities:
- A separate backend component (probably a daemon), that constantly polls and gathers the required data. This would run on a cron-like schedule, or possibly subscribe to message queues where possible. No user interaction is needed to gather information.
- Information is gathered when a user logs into the Delivery Dashboard, presumably by the web backend code.

This may be largely a question for Release Management, and what their expectations are. Eg: are they expecting notifications when things are complete, or just a central place to look for updates.

Feel free to add more possibilies or clarify the above!

**Comment by Natim** [comment]
I would be open to having a queue and a bunch of workers.

Tasks are getting answers about one of the status of one of the release.

We can add tasks automatically when we have an event or when we have a web requests.

We can use WebPush to get updates to the client if the client requested the tasks.

In case a tasks status is still pending, we need somehow to try it later (I guess the client can ask for a refresh)

The status of a task can be ``n/a``, ``queued``, ``started``, ``fail``, ``succeed`` with the last modification date of the status, so that we can retrigger a task if the status is failed and was checked to long ago.

My 2 cents.

**Comment by mostlygeek** [comment]
In general, I think the KISS principle is appropriate here. Even synchronous is fine.

Example for #6 ... 

1. Client (delivery dashboard) makes a request: `GET /bedrock-security-advisories/<version>` 
1. PollBot makes a request: `GET https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/`
1. PollBot scrapes the HTML for `<a>` w/ appropriate `data-version` attributes (https://github.com/mozilla/bedrock/pull/5020)
1. PollBot returns JSON: `{"advisories": [ "url1", "url2", "etc"] }` 
1. Client acts on response

This makes these endpoints stateless. 

Using a Push model requires a much more complex architecture.

**Comment by mozbhearsum** [comment]
I have no strong feelings here personally. The main thing I was trying to get at was an answer to the question "Is RelMan OK with watching/reloading the Delivery Dashboard, or do they want to be notified when things are ready?"

**Comment by mostlygeek** [comment]
Ahh. 

We should have an issue tracking how to do that in the [mozilla/delivery-dashboard](https://github.com/mozilla/delivery-dashboard)  repo once natim spins it up.

**Comment by mostlygeek** [comment]
Closing this issue since the real question is for the Delivery Dashboard.
